# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='VIO.Api.Common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x0eVIO.Api.Common\"\x07\n\x05\x45mpty\"\x1b\n\x0bProtoString\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x0f\x43ommandFeedback\x12\x0e\n\x06status\x18\x01 \x01(\r\"1\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x13\n\x0borientation\x18\x03 \x01(\x02\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x18\n\x08ProtoInt\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"\x19\n\tProtoBool\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x08\"\x1a\n\nProtoFloat\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x02\"&\n\tTimestamp\x12\x0b\n\x03sec\x18\x01 \x01(\r\x12\x0c\n\x04usec\x18\x02 \x01(\r\"\x1c\n\x0cTimestampStr\x12\x0c\n\x04time\x18\x01 \x01(\t\"F\n\x0cPointCloudXY\x12\r\n\x05stamp\x18\x01 \x01(\x01\x12\'\n\x06points\x18\x02 \x03(\x0b\x32\x17.VIO.Api.Common.Point2D*\x94\x01\n\tStateEnum\x12\x0b\n\x07PENDING\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\r\n\tPREEMPTED\x10\x02\x12\r\n\tSUCCEEDED\x10\x03\x12\x0b\n\x07\x41\x42ORTED\x10\x04\x12\x0c\n\x08REJECTED\x10\x05\x12\x0e\n\nPREEMPTING\x10\x06\x12\r\n\tRECALLING\x10\x07\x12\x0c\n\x08RECALLED\x10\x08\x12\x08\n\x04LOST\x10\t*3\n\tLevelEnum\x12\x06\n\x02OK\x10\x00\x12\x08\n\x04WARN\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\t\n\x05STALE\x10\x03\x62\x06proto3'
)

_STATEENUM = _descriptor.EnumDescriptor(
  name='StateEnum',
  full_name='VIO.Api.Common.StateEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREEMPTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCEEDED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABORTED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREEMPTING', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALLING', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALLED', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOST', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=413,
  serialized_end=561,
)
_sym_db.RegisterEnumDescriptor(_STATEENUM)

StateEnum = enum_type_wrapper.EnumTypeWrapper(_STATEENUM)
_LEVELENUM = _descriptor.EnumDescriptor(
  name='LevelEnum',
  full_name='VIO.Api.Common.LevelEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STALE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=563,
  serialized_end=614,
)
_sym_db.RegisterEnumDescriptor(_LEVELENUM)

LevelEnum = enum_type_wrapper.EnumTypeWrapper(_LEVELENUM)
PENDING = 0
ACTIVE = 1
PREEMPTED = 2
SUCCEEDED = 3
ABORTED = 4
REJECTED = 5
PREEMPTING = 6
RECALLING = 7
RECALLED = 8
LOST = 9
OK = 0
WARN = 1
ERROR = 2
STALE = 3



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='VIO.Api.Common.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=39,
)


_PROTOSTRING = _descriptor.Descriptor(
  name='ProtoString',
  full_name='VIO.Api.Common.ProtoString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VIO.Api.Common.ProtoString.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=68,
)


_COMMANDFEEDBACK = _descriptor.Descriptor(
  name='CommandFeedback',
  full_name='VIO.Api.Common.CommandFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='VIO.Api.Common.CommandFeedback.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=103,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='VIO.Api.Common.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='VIO.Api.Common.Pose.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='VIO.Api.Common.Pose.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='VIO.Api.Common.Pose.orientation', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=154,
)


_POINT2D = _descriptor.Descriptor(
  name='Point2D',
  full_name='VIO.Api.Common.Point2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='VIO.Api.Common.Point2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='VIO.Api.Common.Point2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=187,
)


_PROTOINT = _descriptor.Descriptor(
  name='ProtoInt',
  full_name='VIO.Api.Common.ProtoInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VIO.Api.Common.ProtoInt.data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=213,
)


_PROTOBOOL = _descriptor.Descriptor(
  name='ProtoBool',
  full_name='VIO.Api.Common.ProtoBool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VIO.Api.Common.ProtoBool.data', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=240,
)


_PROTOFLOAT = _descriptor.Descriptor(
  name='ProtoFloat',
  full_name='VIO.Api.Common.ProtoFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='VIO.Api.Common.ProtoFloat.data', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=268,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='VIO.Api.Common.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='VIO.Api.Common.Timestamp.sec', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usec', full_name='VIO.Api.Common.Timestamp.usec', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=308,
)


_TIMESTAMPSTR = _descriptor.Descriptor(
  name='TimestampStr',
  full_name='VIO.Api.Common.TimestampStr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='VIO.Api.Common.TimestampStr.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=338,
)


_POINTCLOUDXY = _descriptor.Descriptor(
  name='PointCloudXY',
  full_name='VIO.Api.Common.PointCloudXY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='VIO.Api.Common.PointCloudXY.stamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='VIO.Api.Common.PointCloudXY.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=410,
)

_POINTCLOUDXY.fields_by_name['points'].message_type = _POINT2D
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ProtoString'] = _PROTOSTRING
DESCRIPTOR.message_types_by_name['CommandFeedback'] = _COMMANDFEEDBACK
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Point2D'] = _POINT2D
DESCRIPTOR.message_types_by_name['ProtoInt'] = _PROTOINT
DESCRIPTOR.message_types_by_name['ProtoBool'] = _PROTOBOOL
DESCRIPTOR.message_types_by_name['ProtoFloat'] = _PROTOFLOAT
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['TimestampStr'] = _TIMESTAMPSTR
DESCRIPTOR.message_types_by_name['PointCloudXY'] = _POINTCLOUDXY
DESCRIPTOR.enum_types_by_name['StateEnum'] = _STATEENUM
DESCRIPTOR.enum_types_by_name['LevelEnum'] = _LEVELENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.Empty)
  })
_sym_db.RegisterMessage(Empty)

ProtoString = _reflection.GeneratedProtocolMessageType('ProtoString', (_message.Message,), {
  'DESCRIPTOR' : _PROTOSTRING,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.ProtoString)
  })
_sym_db.RegisterMessage(ProtoString)

CommandFeedback = _reflection.GeneratedProtocolMessageType('CommandFeedback', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDFEEDBACK,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.CommandFeedback)
  })
_sym_db.RegisterMessage(CommandFeedback)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.Pose)
  })
_sym_db.RegisterMessage(Pose)

Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), {
  'DESCRIPTOR' : _POINT2D,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.Point2D)
  })
_sym_db.RegisterMessage(Point2D)

ProtoInt = _reflection.GeneratedProtocolMessageType('ProtoInt', (_message.Message,), {
  'DESCRIPTOR' : _PROTOINT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.ProtoInt)
  })
_sym_db.RegisterMessage(ProtoInt)

ProtoBool = _reflection.GeneratedProtocolMessageType('ProtoBool', (_message.Message,), {
  'DESCRIPTOR' : _PROTOBOOL,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.ProtoBool)
  })
_sym_db.RegisterMessage(ProtoBool)

ProtoFloat = _reflection.GeneratedProtocolMessageType('ProtoFloat', (_message.Message,), {
  'DESCRIPTOR' : _PROTOFLOAT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.ProtoFloat)
  })
_sym_db.RegisterMessage(ProtoFloat)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

TimestampStr = _reflection.GeneratedProtocolMessageType('TimestampStr', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPSTR,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.TimestampStr)
  })
_sym_db.RegisterMessage(TimestampStr)

PointCloudXY = _reflection.GeneratedProtocolMessageType('PointCloudXY', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUDXY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VIO.Api.Common.PointCloudXY)
  })
_sym_db.RegisterMessage(PointCloudXY)


# @@protoc_insertion_point(module_scope)
