// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace VIO {
namespace Api {
namespace ServiceRpc {

class Rpc final {
 public:
  static constexpr char const* service_full_name() {
    return "VIO.Api.ServiceRpc.Rpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Check
    // @return Common.StateEnum
    virtual ::grpc::Status CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::VIO::Api::Common::CommandFeedback* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::CommandFeedback>> AsyncCheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::CommandFeedback>>(AsyncCheckCommunicationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::CommandFeedback>> PrepareAsyncCheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::CommandFeedback>>(PrepareAsyncCheckCommunicationRaw(context, request, cq));
    }
    // @RPC_ID=0
    // SuperPoint
    virtual ::grpc::Status GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::VIO::Api::Common::PointCloudXY* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::PointCloudXY>> AsyncGetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::PointCloudXY>>(AsyncGetSuperPointRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::PointCloudXY>> PrepareAsyncGetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::PointCloudXY>>(PrepareAsyncGetSuperPointRaw(context, request, cq));
    }
    // @RPC_ID=1
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Check
      // @return Common.StateEnum
      virtual void CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckCommunication(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::CommandFeedback* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CheckCommunication(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CheckCommunication(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // @RPC_ID=0
      // SuperPoint
      virtual void GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSuperPoint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::PointCloudXY* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetSuperPoint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetSuperPoint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // @RPC_ID=1
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::CommandFeedback>* AsyncCheckCommunicationRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::CommandFeedback>* PrepareAsyncCheckCommunicationRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::PointCloudXY>* AsyncGetSuperPointRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::VIO::Api::Common::PointCloudXY>* PrepareAsyncGetSuperPointRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::VIO::Api::Common::CommandFeedback* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::CommandFeedback>> AsyncCheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::CommandFeedback>>(AsyncCheckCommunicationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::CommandFeedback>> PrepareAsyncCheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::CommandFeedback>>(PrepareAsyncCheckCommunicationRaw(context, request, cq));
    }
    ::grpc::Status GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::VIO::Api::Common::PointCloudXY* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::PointCloudXY>> AsyncGetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::PointCloudXY>>(AsyncGetSuperPointRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::PointCloudXY>> PrepareAsyncGetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::PointCloudXY>>(PrepareAsyncGetSuperPointRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response, std::function<void(::grpc::Status)>) override;
      void CheckCommunication(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::CommandFeedback* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CheckCommunication(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CheckCommunication(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CheckCommunication(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::CommandFeedback* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response, std::function<void(::grpc::Status)>) override;
      void GetSuperPoint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::PointCloudXY* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetSuperPoint(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetSuperPoint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetSuperPoint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::VIO::Api::Common::PointCloudXY* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::CommandFeedback>* AsyncCheckCommunicationRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::CommandFeedback>* PrepareAsyncCheckCommunicationRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::PointCloudXY>* AsyncGetSuperPointRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::VIO::Api::Common::PointCloudXY>* PrepareAsyncGetSuperPointRaw(::grpc::ClientContext* context, const ::VIO::Api::Common::ProtoString& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckCommunication_;
    const ::grpc::internal::RpcMethod rpcmethod_GetSuperPoint_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Check
    // @return Common.StateEnum
    virtual ::grpc::Status CheckCommunication(::grpc::ServerContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response);
    // @RPC_ID=0
    // SuperPoint
    virtual ::grpc::Status GetSuperPoint(::grpc::ServerContext* context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response);
    // @RPC_ID=1
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckCommunication() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCommunication(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckCommunication(::grpc::ServerContext* context, ::VIO::Api::Common::ProtoString* request, ::grpc::ServerAsyncResponseWriter< ::VIO::Api::Common::CommandFeedback>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSuperPoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSuperPoint() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetSuperPoint() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSuperPoint(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSuperPoint(::grpc::ServerContext* context, ::VIO::Api::Common::ProtoString* request, ::grpc::ServerAsyncResponseWriter< ::VIO::Api::Common::PointCloudXY>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckCommunication<WithAsyncMethod_GetSuperPoint<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CheckCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_CheckCommunication() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::CommandFeedback>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::CommandFeedback* response) { return this->CheckCommunication(context, request, response); }));}
    void SetMessageAllocatorFor_CheckCommunication(
        ::grpc::experimental::MessageAllocator< ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::CommandFeedback>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::CommandFeedback>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CheckCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCommunication(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CheckCommunication(
      ::grpc::CallbackServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CheckCommunication(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetSuperPoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetSuperPoint() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::PointCloudXY>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::VIO::Api::Common::ProtoString* request, ::VIO::Api::Common::PointCloudXY* response) { return this->GetSuperPoint(context, request, response); }));}
    void SetMessageAllocatorFor_GetSuperPoint(
        ::grpc::experimental::MessageAllocator< ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::PointCloudXY>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::PointCloudXY>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetSuperPoint() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSuperPoint(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetSuperPoint(
      ::grpc::CallbackServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetSuperPoint(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_CheckCommunication<ExperimentalWithCallbackMethod_GetSuperPoint<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_CheckCommunication<ExperimentalWithCallbackMethod_GetSuperPoint<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckCommunication() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCommunication(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetSuperPoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSuperPoint() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetSuperPoint() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSuperPoint(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckCommunication() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCommunication(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckCommunication(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSuperPoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSuperPoint() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetSuperPoint() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSuperPoint(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSuperPoint(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CheckCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_CheckCommunication() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckCommunication(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_CheckCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCommunication(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CheckCommunication(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CheckCommunication(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetSuperPoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetSuperPoint() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSuperPoint(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetSuperPoint() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSuperPoint(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetSuperPoint(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetSuperPoint(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckCommunication : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckCommunication() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::CommandFeedback>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::CommandFeedback>* streamer) {
                       return this->StreamedCheckCommunication(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckCommunication() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckCommunication(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::CommandFeedback* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckCommunication(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::VIO::Api::Common::ProtoString,::VIO::Api::Common::CommandFeedback>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSuperPoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSuperPoint() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::PointCloudXY>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::VIO::Api::Common::ProtoString, ::VIO::Api::Common::PointCloudXY>* streamer) {
                       return this->StreamedGetSuperPoint(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSuperPoint() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSuperPoint(::grpc::ServerContext* /*context*/, const ::VIO::Api::Common::ProtoString* /*request*/, ::VIO::Api::Common::PointCloudXY* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSuperPoint(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::VIO::Api::Common::ProtoString,::VIO::Api::Common::PointCloudXY>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckCommunication<WithStreamedUnaryMethod_GetSuperPoint<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckCommunication<WithStreamedUnaryMethod_GetSuperPoint<Service > > StreamedService;
};

}  // namespace ServiceRpc
}  // namespace Api
}  // namespace VIO


#endif  // GRPC_service_2eproto__INCLUDED
